### ISSUE TITLE
Light intensity below epibenthos (model: 'EpiPAR', sensor: '', standard: ''')

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/ereefs#11]
Full description:
Mean downwelling photosynthetically available radiation (400 - 700nm) at the _sediment-water interface._

Currently mapped to the NVS as:
Downwelling vector irradiance as energy of electromagnetic radiation (PAR wavelengths) _per unit area of the bed_ by model prediction

Is 'per unit area of the bed' acceptable in lieu of an  existing term for 'sediment-water interface.'?

Is it important to state that it is an average, if so the term would be:
Downwelling vector irradiance as energy _mean_ of electromagnetic radiation (PAR wavelengths) _per unit area of the bed_ by model prediction

**Comment by markebaird** [comment]
Hi, 'per unit area of the bed' is correct. The point of saying 'at the sediment-water interface' is that it is at the seabed. Perhaps you would rather sedbed? In hindsight, I don't think my use of 'mean' is correct, because it is an instantaneous in time value and the integral over the wavelength from 400 - 700 nm.

So perhaps it should be: Downwelling vector irradiance as energy of electromagnetic radiation (integrated over PAR wavelengths) per unit area of the bed by model prediction

**Comment by roswri** [comment]
thanks @markebaird !

I have a related question for: Av. PAR in layer (model: 'PAR', sensor: '', standard: ''') 
description: Mean scalar photosynthetically available radiation (400 - 700 nm) within the layer.

Is mean important to specify here? e.g. 4-pi scalar irradiance as photons mean of electromagnetic radiation (PAR wavelengths) per unit area of the water body by model prediction

**Comment by markebaird** [comment]
I agree mean should not be there. Rewording your phase slightly, it should be: "4-pi scalar irradiance as photons of electromagnetic radiation (PAR wavelengths) per unit area of the water body by model prediction"

**Comment by markebaird** [comment]
But we do have a running mean (I have tried to attached a document describing this). In any case, the instantaneous value is a different variable to the time-accumulated.

**Comment by markebaird** [comment]
see attached file:

**Comment by gwemon** [comment]
@markebaird the file attachment has not come through. Could you send it to vocab.services@bodc.ac.uk please? Many thanks.

**Comment by roswri** [comment]
Hi @markebaird,

Just to confirm; these parameter codes that I'm creating are for the instantaneous values not the running mean?

**Option 1 - instantaneous values:**
- 4-pi scalar irradiance as photons  of electromagnetic radiation (PAR wavelengths) per unit time per unit area of the water body by model prediction
- Downwelling vector irradiance as energy  of electromagnetic radiation (PAR wavelengths) per unit area of the bed by model prediction

**Option 2 - running mean:**
- 4-pi scalar irradiance as photons hourly mean of electromagnetic radiation (PAR wavelengths) per unit time per unit area of the water body by model prediction
- Downwelling vector irradiance as energy hourly mean of electromagnetic radiation (PAR wavelengths) per unit area of the bed by model prediction

**Comment by gwemon** [comment]
@roswri  if we need terms for the running means we will need to define running mean in S07 because an hourly mean is not the same as a hourly running mean. See: https://en.wikipedia.org/wiki/Moving_average

**Comment by markebaird** [comment]
Hi,

Almost all our model outputs are instantaneous values. EpiPAR is an example, so below option 1 is correct.

Occasionally we have time-average values. For example, at OPeNDAP Dataset Query Form (nci.org.au)<https://dapds00.nci.org.au/thredds/dodsC/fx3/gbr4_bgc_GBR4_H2p0_B3p0_Chyd_Dcrt/gbr4_bgc_all_simple_2018-10.nc.html> we have a data set with both the instantaneous value of PAR light (in this case above the seagrass), EpiPAR_sg, and the running mean on a monthly time scale of the same quantity, month_EpiPAR_sg (I have snapshotted the entries in the opendap below).

As you point out there a number of ways of calculating the mean, so perhaps rather than having a unique vocab for month_EpiPAR_sg, it should just refer to entries for EpiPAR_sg and running mean.

Two minor points:

1. As a side note, I should have described month_EpiPAR_sg as a monthly running-mean.
2. Running mean in our output always refers to times up to the present, so is not quite like a low pass filter that are referred to in the Wikipedia entry. This allows us to calculate the mean based only on the mean at the last time point and the new value, saving a lot of memory compared to a moving wind for which all values in the last say 30 days need to be kept.

Thanks,

Mark

***@***.***

**Comment by gwemon** [comment]
Thank you @markebaird so if I understand correctly all what the project needs at this stage are P01 codes for the instantaneous concepts. It can be decided later whether codes are also needed for the monthly running-averages. Is that correct? Capturing the subtleties related to the calculation of means can be tricky indeed! We do have a term for monthly mean that uses a quite broad (cautious) definition and could be sufficient in relation to month_EpiPAR_sg: http://vocab.nerc.ac.uk/collection/S07/current/S0700016/

**Comment by markebaird** [comment]
Thank you @markebaird<https://github.com/markebaird> so if I understand correctly all what the project needs at this stage are P01 codes for the instantaneous concepts.
Yes.
