### ISSUE TITLE
Bleach rate - zooxanthellae loss quantification and units

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/ereefs#13]
In relation to the following parameter (BODC sheet primary key 6)
06 - Coral bleach rate (model: 'CS_bleach', sensor: '', standard: ''')

Do you have any input on how best the loss should be termed? E.g.:
Loss of zooxanthellae biomass as nitrogen
Loss of zooxanthellae individuals
Loss of zooxanthellae cells 

____________________

Secondly, the unit provided for this parameter is per day (d-1), should this parameter also be related to area or mass of coral (tissue), in other words bound by an area sampled/modelled, e.g. per unit time per unit area of the bed? 

Similar loss rate parameters have been area bound, with suggested P06 units [GSMD - grams per square metre per day:](https://vocab.nerc.ac.uk/collection/P06/current/GSMD/) and CSIRO units provided as **g N m-2 d-1**
152 - Seagrass shear stress mort (model: 'SG_shear_mort', sensor: '', standard: ''')
155 - Deep seagrass shear stress mort (model: 'SGD_shear_mort', sensor: '', standard: ''')
159 - Halophila shear stress mort (model: 'SGH_shear_mort', sensor: '', standard: ''')

**Comment by markebaird** [comment]
This is a diagnostic variable that will not necessarily be used in all EMS applications. Perhaps the best phrasing would be "exponential loss rate of zooxanthellae cells due to expulsion"

Given this definition, the units are okay.

**Comment by gwemon** [comment]
@JordanAthertonNOC  I wonder if, instead of defining this in relation to the loss of zooxanthellae, we might not be better defining it as a bleaching rate. So we could create a parameter code of the form: 
"Bleaching rate of coral in the water body by model prediction"
where:
Bleaching rate could be defined as: "Rate over time at which an object becomes discoloured."
The full P01 could be defined as:
"Rate over time at which corals become bleached and turn white, as simulated by a numerical model. Coral bleaching is the result of the expulsion of the coral's symbiotic microalgae (zooxanthellae) from the coral host tissue in response to one or multiple environmental stress factors." 
Units "per day" would then be fine.
@markebaird would that label and definition fit your parameter?

**Comment by gwemon** [comment]
@markebaird  to summarise, our proposal for this parameter is: 
**Preferred label**: "Bleaching rate of coral in the water body by model prediction"
**Definition**: "Rate over time at which corals become bleached and turn white, as simulated by a numerical model. Coral bleaching is the result of the expulsion of the coral's symbiotic microalgae (zooxanthellae) from the coral host tissue in response to one or multiple environmental stress factors."

**Comment by markebaird** [comment]
I would prefer defining bleaching in terms of zooxanthellae loss. Colour change depends on many things (e.g. pigment content of cells, number of cells, skeleton colour etc.) and can be calculated separately in the model. There are also qualitative colour charts (https://www.google.com/url?sa=i&url=https%3A%2F%2Fcoralwatch.org%2Findex.php%2Fproduct%2Fcoral-health-chart%2F&psig=AOvVaw0T0I2oF-Um_ViAqBeTuiYn&ust=1652955415303000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJCzp_Xo6PcCFQAAAAAdAAAAABAD) which we are not trying to replicate. Thanks, Mark

**Comment by gwemon** [comment]
@markebaird Could you point us to a publication where this parameter is defined please? I am struggling to construct the parameter code label in such a way that it can have units of "per day". Seeing it defined in context might help.

**Comment by markebaird** [comment]
Hi Gwen,

I haven’t defined this explicitly in our published papers because it is a diagnostic variable. 

Nonetheless, in the attached paper, Table 29 is the equations for all the model variables that are reduced by expulsion. If you take Eq. 173 and divide the right hand by CS, you get the mass-specific rate at which they are expelled, which is what we are calling the bleaching rate in the output. It which has the same units as gamma, the maximum expulsion rate.

Thanks,

Mark

Paper at: https://gmd.copernicus.org/articles/13/4503/2020/

**Comment by JordanAthertonNOC** [comment]
Term ready to be created as follows:

https://github.com/nvs-vocabs/P01/issues/156
