### ISSUE TITLE
Seagrass loss parameters

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/ereefs#19]
In relation to the following three parameters (BODC sheet primary keys 152, 155 and 159)
152 - Seagrass shear stress mort (model: 'SG_shear_mort', sensor: '', standard: ''')
155 - Deep seagrass shear stress mort (model: 'SGD_shear_mort', sensor: '', standard: ''')
159 - Halophila shear stress mort (model: 'SGH_shear_mort', sensor: '', standard: ''')

1. Should 152 and 155 relate to 'seagrass' or a particular species/genus of seagrass as has been the case for other requested seagrass parameters (e.g. BODC PK 11).
2. Does 152 encompass 'all' seagrass or is this term intended as a distinction from 155 - deep seagrass (i.e. in this case shallow).
3. Similar to question 1, term 159 is specified as the genus Halophila - just double checking this is correct at the genus level.

**Comment by markebaird** [comment]
In some of our applications we only have one seagrass state variable, called seagrass. In the GBR we added two more "Halophila" and "Deep Seagrass" to the original variable to give three types. I can see now see this is confusing, but it is a bt late to change. When I published this model the ecologists were keen for me to consider these variables as seagrass types, not species, because I was not specific enough. Perhaps using the phrase 'type' would help.

In general the model naming has this same problem in many variables. e.g. if I have Large and Small Zooplankton, but then remove Small Zooplankton, then Large Zooplankton represents all zooplankton, not just 'Large' ones.

**Comment by gwemon** [comment]
@markebaird I like the idea of using "type". We do have a way to do this in our semantic model, See e.g. http://vocab.nerc.ac.uk/collection/S25/current/BE007385/
So in our case here we would need to relate these loss rates to 3 new biological entity records:
One for just "seagrasses"
One for "seagrasses [Subgroup: Halophila decipiens type]"
One for "seagrasses [Subgroup: Halophila ovalis type]"

Or shall we go for the following types as mentioned in your paper: "seagrass types corresponding to Zostera, Halophila, deep Halophila". 
Hence we would have:
"seagrass [Subgroup: Zostera type]"
"seagrass[Subgroup: deep Halophila type]"
"seagrass [Subgroup: shallow Halophila type]"
?

I like the former become somebody looking for "Halophila decipiens" or "Halophila ovalis" would find them. It also ties in with the codes @roswri created for the biomass as nitrogen of H. decipiens and H. ovalis too.

**Comment by markebaird** [comment]
Yes, I prefer the former too. Thank, Mark
