### ISSUE TITLE
Total Chlorophyll (model: 'Chl_a_sum', sensor: '', standard: ''')

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/ereefs#8]
In relation to the following parameter (BODC sheet primary key 1)
01 - Total Chlorophyll (model: 'Chl_a_sum', sensor: '', standard: ''')

The parameter description refers to 'four microalgae types'. These are listed here under total chlorophyll:
https://ereefs.aims.gov.au/ereefs-aims/gbr4/bgc/baseline/chl-a-sum_din_efi

One such type is 'microphytobenthos' (i.e. benthic microalgae living in association with benthic substrates). Querying whether the matrix (S26) for this parameter should refer to the **water body**, or the **water body plus sediment** in order to also accommodate these benthic microalgae.

**Comment by markebaird** [comment]
The microphytobenthos are microalgal cells with a fast sinking rate. During resuspension events they are introduced into the water.  So they should be "water body plus sediment"

**Comment by JordanAthertonNOC** [comment]
Thanks Mark.

**Comment by gwemon** [comment]
@JordanAthertonNOC @markebaird if these microphytobenthos cells are included in "total chla" as part of sediment resuspension events then the matrix should still be "water body [particulate phase]" because if you take the equivalent using in situ measurements these would still be analysed in a sample of water and not in a sample of sediment; so the matrix is the water. Also @JordanAthertonNOC please just use "water body" for this, similar to the existing term for simulated chl-a (not yet expressed according to the PUV semantic model but will do this today so should be live tomorrow): http://vocab.nerc.ac.uk/collection/P01/current/CPHLMMMO/
